const themeArray = [
	{ key: 'null', value: '', text: ''},
	{ key: 'magie', value: 'magie', text: 'Magie'},
	{ key: 'bombe', value: 'bombe', text: 'Bombe'},
	{ key: 'intelligence_artificelle', value: 'intelligence_artificelle', text: 'Intelligence artificelle'},
	{ key: 'jungle', value: 'jungle', text: 'Jungle'},
	{ key: 'futuriste', value: 'futuriste', text: 'Futuriste'},
	{ key: 'horreur', value: 'horreur', text: 'Horreur'},
	{ key: 'hôpital', value: 'hôpital', text: 'Hôpital'},
	{ key: 'bunker', value: 'bunker', text: 'Bunker'},
	{ key: 'banque', value: 'banque', text: 'Banque'},
	{ key: 'casino', value: 'casino', text: 'Casino'},
	{ key: 'enquête', value: 'enquête', text: 'Enquête'},
	{ key: 'asile', value: 'asile', text: 'Asile'},
	{ key: 'laboratoire', value: 'laboratoire', text: 'Laboratoire'},
	{ key: 'médiéval', value: 'médiéval', text: 'Médiéval'},
	{ key: 'voyage_dans_le_temps', value: 'voyage_dans_le_temps', text: 'Voyage dans le temps'},
	{ key: 'prison', value: 'prison', text: 'Prison'},
	{ key: 'mexique', value: 'mexique', text: 'Mexique'},
	{ key: 'entretien', value: 'entretien', text: 'Entretien'},
	{ key: 'spatial', value: 'spatial', text: 'Spatial'},
	{ key: 'fantôme', value: 'fantôme', text: 'Fantôme'},
	{ key: 'conte_de_fée', value: 'conte_de_fée', text: 'Conte de fée'},
	{ key: 'egypte', value: 'egypte', text: 'Egypte'},
	{ key: 'archéologie', value: 'archéologie', text: 'Archéologie'},
	{ key: 'agent_secret', value: 'agent_secret', text: 'Agent secret'},
	{ key: 'avion', value: 'avion', text: 'Avion'},
	{ key: 'vampire', value: 'vampire', text: 'Vampire'},
	{ key: 'far_west', value: 'far_west', text: 'Far West'},
	{ key: 'malédiction', value: 'malédiction', text: 'Malédiction'},
	{ key: 'hacking', value: 'hacking', text: 'Hacking'},
	{ key: 'monument_parisien', value: 'monument_parisien', text: 'Monument parisien'},
	{ key: 'inédit', value: 'inédit', text: 'Inédit'},
	{ key: 'zombie', value: 'zombie', text: 'Zombie'},
	{ key: 'métro', value: 'métro', text: 'Métro'},
	{ key: 'pirate', value: 'pirate', text: 'Pirate'},
	{ key: 'sous-marin', value: 'sous-marin', text: 'Sous-marin'},
	{ key: 'espionnage', value: 'espionnage', text: 'Espionnage'},
	{ key: 'voyage', value: 'voyage', text: 'Voyage'},
	{ key: 'histoire', value: 'histoire', text: 'Histoire'},
	{ key: 'bateau', value: 'bateau', text: 'Bateau'},
	{ key: 'japon', value: 'japon', text: 'Japon'},
	{ key: 'monument_parisien', value: 'monument_parisien', text: 'Monument parisien'},
	{ key: 'gueule_de_bois', value: 'gueule_de_bois', text: 'Gueule de bois'},
	{ key: 'réalité_virtuelle', value: 'réalité_virtuelle', text: 'Réalité virtuelle'}
]

export default themeArray;